### ISSUE TITLE
deploy script

### ISSUE THREAD

**Issue by rthrblck** [rthrblck/arthurblackdesign#1]
Add and configure plugin to deploy built site to gh-pages.

**Comment by christianbundy** [comment]
You might like [this grunt plugin](https://github.com/tschaub/grunt-gh-pages).

**Comment by christianbundy** [comment]
I think this was solved by bfb7f3b193f25dded8f2bead7a2420b45b921e6a.

**Comment by rthrblck** [comment]
yes indeed, thanks for the help!
